name       : perl-alien-sdl
version    : 1.446
release    : 3
source     :
    - https://cpan.metacpan.org/authors/id/F/FR/FROGGS/Alien-SDL-1.446.tar.gz : c9aa2c9dc3c63d89773c7d7203f2a46d1b924d0c72d9f801af147a3dc8bc512a
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Building, finding and using SDL binaries
description: |
    In short Alien::SDL can be used to detect and get configuration settings from an installed SDL and related libraries. Based on your platform it offers the possibility to download and install prebuilt binaries or to build SDL & co. from source codes.
builddeps  :
    - pkgconfig(SDL_Pango)
    - pkgconfig(SDL_gfx)
    - pkgconfig(SDL_image)
    - pkgconfig(SDL_mixer)
    - pkgconfig(SDL_ttf)
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
    - pkgconfig(vorbis)
    - perl-archive-extract
    - perl-archive-zip
    - perl-capture-tiny
    - perl-file-sharedir
    - perl-file-which
    - perl-module-build
    - perl-text-patch
rundeps    :
    - perl-capture-tiny
    - perl-file-sharedir
    - perl-file-which
build      : |
    %perl_setup --travis
install    : |
    %perl_install
check      : |
    perl Build test
